apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  selector: { app: sbom-security-toolkit, component: web }
  ports:
    - name: http
      port: 80
      targetPort: 8080
