#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, os, shutil, sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_CONFIG = {
    "mode": "local",
    "storage_backend": "filesystem",
    "object_storage": {
        "s3_bucket": "",
        "s3_prefix": "sbom-security-toolkit/",
        "endpoint_url": "",
        "region": "us-east-1"
    },
    "database": {
        "url_env": "DATABASE_URL",
        "default_local_url": "sqlite:///projects/history.db"
    },
    "queue": {
        "url_env": "REDIS_URL",
        "default_local_url": "redis://redis:6379/0"
    },
    "auth": {
        "enabled": False,
        "mode": "local-admin",
        "oidc_issuer": "",
        "oidc_client_id_env": "SST_OIDC_CLIENT_ID"
    },
    "ai": {
        "provider": "none",
        "allow_external_ai": False,
        "redact_before_prompt": True
    },
    "safety": {
        "execute_project_code": False,
        "run_install_scripts": False,
        "allow_remote_git_clone": False,
        "log_secrets": False,
        "api_runs_fuzzing_inline": False
    }
}


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


def cmd_init(args: argparse.Namespace) -> int:
    path = Path(args.output)
    config = dict(DEFAULT_CONFIG)
    if args.mode:
        config["mode"] = args.mode
    if args.storage:
        config["storage_backend"] = args.storage
    write_json(path, config)
    print(path)
    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    checks = []
    for name, binary in [
        ("git", "git"), ("docker", "docker"), ("docker compose", "docker"),
        ("python3", "python3"), ("redis-cli", "redis-cli"), ("psql", "psql"), ("aws", "aws"),
    ]:
        checks.append({"name": name, "available": shutil.which(binary) is not None})
    env_checks = []
    for name in ["DATABASE_URL", "REDIS_URL", "SST_ADMIN_PASSWORD", "SST_OBJECT_BUCKET", "AWS_REGION"]:
        env_checks.append({"name": name, "configured": bool(os.environ.get(name))})
    report = {
        "checked_at": datetime.now(timezone.utc).isoformat(),
        "deployment_mode": os.environ.get("SST_DEPLOYMENT_MODE", "local"),
        "tools": checks,
        "environment": env_checks,
        "safety_defaults": DEFAULT_CONFIG["safety"],
        "notes": [
            "Cloud mode is self-hosted and opt-in.",
            "Run fuzzing in workers, not in the API container.",
            "Use IAM roles or secret managers for tokens; do not store credentials in job JSON or logs.",
        ],
    }
    if args.out:
        write_json(Path(args.out), report)
    print(json.dumps(report, indent=2))
    return 0


def cmd_schedule_template(args: argparse.Namespace) -> int:
    out = Path(args.output)
    text = f"""#!/usr/bin/env bash
set -euo pipefail
# Local cron/cloud scheduler template generated by SBOM Security Toolkit.
# Example cron entry: 0 6 * * * /path/to/{out.name}
cd "${{SST_PROJECT_DIR:-$(pwd)}}"
python3 -m sbomops.repo_intake analyze "${{SST_REPO_SOURCE:-.}}" \
  --out-dir "${{SST_REPORT_DIR:-reports/scheduled/$(date +%Y%m%d-%H%M%S)}}" \
  --generators "${{SST_REPO_GENERATORS:-auto}}" \
  --policy "${{SST_POLICY:-policies/default-release-policy.yml}}" \
  ${{SST_EXTRA_ARGS:-}}
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    out.chmod(0o755)
    print(out)
    return 0


def cmd_worker_entrypoint(args: argparse.Namespace) -> int:
    print("SBOM Security Toolkit worker placeholder")
    print("queue=", os.environ.get("SST_WORKER_QUEUE", "default"))
    print("mode=", os.environ.get("SST_DEPLOYMENT_MODE", "server"))
    print("This lightweight worker entrypoint is a safe scaffold; wire it to your preferred queue backend before production use.")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Cloud/self-hosted helpers for SBOM Security Toolkit")
    sub = ap.add_subparsers(dest="cmd", required=True)
    init = sub.add_parser("init-config")
    init.add_argument("--output", default="cloud/sst-cloud-config.json")
    init.add_argument("--mode", choices=["local", "server"], default="server")
    init.add_argument("--storage", choices=["filesystem", "s3"], default="s3")
    init.set_defaults(func=cmd_init)
    doctor = sub.add_parser("doctor")
    doctor.add_argument("--out")
    doctor.set_defaults(func=cmd_doctor)
    sched = sub.add_parser("schedule-template")
    sched.add_argument("--output", default="cloud/run-scheduled-scan.sh")
    sched.set_defaults(func=cmd_schedule_template)
    worker = sub.add_parser("worker")
    worker.set_defaults(func=cmd_worker_entrypoint)
    args = ap.parse_args(argv)
    return args.func(args)

if __name__ == "__main__":
    raise SystemExit(main())
