#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
import smtplib
import urllib.request
from datetime import datetime, timezone
from email.message import EmailMessage
from pathlib import Path
from typing import Any, Dict, List

try:
    import yaml  # type: ignore
except Exception:  # pragma: no cover
    yaml = None

from .common import parse_components

ROOT = Path(__file__).resolve().parents[1]


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def write_text(path: Path, text: str) -> Path:
    ensure_dir(path.parent)
    path.write_text(text, encoding="utf-8")
    return path


def write_json(path: Path, data: Any) -> Path:
    return write_text(path, json.dumps(data, indent=2, sort_keys=False) + "\n")


def write_yaml(path: Path, data: Any) -> Path:
    if yaml:
        return write_text(path, yaml.safe_dump(data, sort_keys=False))
    return write_json(path, data)


def load_json(path: str | Path, default: Any = None) -> Any:
    p = Path(path)
    if not p.exists():
        return default
    try:
        return json.loads(p.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return default


def finding_fingerprint(*parts: str) -> str:
    return hashlib.sha256("|".join(parts).encode()).hexdigest()[:16]


def component_findings(sbom: str | Path) -> List[Dict[str, Any]]:
    p = Path(sbom)
    findings: List[Dict[str, Any]] = []
    try:
        _fmt, comps, _meta = parse_components(p)
        for c in comps:
            name = c.name or c.bom_ref or "unknown"
            version = c.version or ""
            purl = c.purl or ""
            if not version:
                findings.append({
                    "rule_id": "SST-MISSING-VERSION",
                    "level": "warning",
                    "title": "Component missing exact version",
                    "message": f"Component {name} does not declare an exact version.",
                    "component": name,
                    "version": version,
                    "purl": purl,
                    "fingerprint": finding_fingerprint("missing-version", name, purl),
                })
            if version and any(x in version.lower() for x in ["snapshot", "latest", "dev", "*"]):
                findings.append({
                    "rule_id": "SST-UNPINNED-VERSION",
                    "level": "warning",
                    "title": "Component appears unpinned or pre-release",
                    "message": f"Component {name} has version value {version!r}, which may be unpinned or unstable.",
                    "component": name,
                    "version": version,
                    "purl": purl,
                    "fingerprint": finding_fingerprint("unpinned", name, version, purl),
                })
    except Exception as exc:
        findings.append({
            "rule_id": "SST-SBOM-PARSE-ERROR",
            "level": "error",
            "title": "SBOM parsing failed",
            "message": str(exc),
            "component": str(p),
            "version": "",
            "purl": "",
            "fingerprint": finding_fingerprint("parse-error", str(p), str(exc)),
        })
    if not findings:
        findings.append({
            "rule_id": "SST-SBOM-OBSERVED",
            "level": "note",
            "title": "SBOM parsed successfully",
            "message": "No default export findings were generated by local heuristics.",
            "component": p.name,
            "version": "",
            "purl": "",
            "fingerprint": finding_fingerprint("observed", str(p)),
        })
    return findings


def export_sarif(args: argparse.Namespace) -> Dict[str, Any]:
    findings = component_findings(args.sbom) if args.sbom else []
    release = load_json(args.release_decision, {}) if getattr(args, "release_decision", "") else {}
    if release and release.get("decision") in {"warn", "block"}:
        level = "error" if release.get("decision") == "block" else "warning"
        findings.append({
            "rule_id": "SST-RELEASE-DECISION",
            "level": level,
            "title": f"Release decision: {release.get('decision')}",
            "message": "; ".join(release.get("reasons", [])) or "Release decision produced a non-pass result.",
            "component": "release",
            "version": "",
            "purl": "",
            "fingerprint": finding_fingerprint("release-decision", json.dumps(release, sort_keys=True)),
        })
    rules: Dict[str, Dict[str, Any]] = {}
    results: List[Dict[str, Any]] = []
    for f in findings:
        rid = f["rule_id"]
        rules[rid] = {"id": rid, "name": f["title"], "shortDescription": {"text": f["title"]}, "help": {"text": f["message"]}}
        results.append({
            "ruleId": rid,
            "level": f.get("level", "warning"),
            "message": {"text": f.get("message", "")},
            "locations": [{"physicalLocation": {"artifactLocation": {"uri": str(args.sbom or "sbom")}, "region": {"startLine": 1}}}],
            "partialFingerprints": {"sstFinding": f.get("fingerprint", finding_fingerprint(rid, f.get("message", "")))},
            "properties": {"component": f.get("component", ""), "version": f.get("version", ""), "purl": f.get("purl", "")},
        })
    sarif = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {"name": "SBOM Security Toolkit", "semanticVersion": "2.5.0", "informationUri": "https://github.com/hellnbak/sbom_security_toolkit", "rules": list(rules.values())}},
            "automationDetails": {"id": getattr(args, "project", "") or "local"},
            "results": results,
            "properties": {"created_at": now(), "source": "sst export sarif"},
        }],
    }
    out = Path(args.out)
    write_json(out, sarif)
    return {"path": str(out), "findings": len(results), "rules": len(rules)}


def export_openvex(args: argparse.Namespace) -> Dict[str, Any]:
    _fmt, comps, _meta = parse_components(Path(args.sbom))
    statements = []
    for c in comps:
        subject = {"name": c.name or c.bom_ref or "unknown"}
        if c.purl:
            subject["identifiers"] = {"purl": c.purl}
        elif c.bom_ref:
            subject["identifiers"] = {"bom-ref": c.bom_ref}
        statements.append({
            "vulnerability": {"name": args.vulnerability or "UNSPECIFIED"},
            "timestamp": now(),
            "products": [{"@id": subject.get("identifiers", {}).get("purl", subject["name"]), "subcomponents": [subject]}],
            "status": args.status,
            "justification": args.justification,
            "impact_statement": args.impact_statement,
            "action_statement": args.action_statement,
        })
    doc = {"@context": "https://openvex.dev/ns/v0.2.0", "@id": f"urn:sst:openvex:{finding_fingerprint(str(args.sbom), now())}", "author": args.author, "timestamp": now(), "version": 1, "statements": statements}
    out = Path(args.out)
    write_json(out, doc)
    return {"path": str(out), "statements": len(statements), "status": args.status}


def export_jira(args: argparse.Namespace) -> Dict[str, Any]:
    issues = []
    for f in component_findings(args.sbom):
        issues.append({"project": args.project_key, "issuetype": args.issue_type, "summary": f"[{f['rule_id']}] {f['title']}: {f.get('component','')}", "description": f.get("message", ""), "labels": ["sbom-security-toolkit", "supply-chain"], "external_fingerprint": f.get("fingerprint"), "component": f.get("component", ""), "purl": f.get("purl", "")})
    out = Path(args.out)
    write_json(out, {"generated_at": now(), "mode": "dry-run", "issues": issues})
    return {"path": str(out), "issues": len(issues), "note": "Dry-run Jira payload only; no network call performed."}


def export_defectdojo(args: argparse.Namespace) -> Dict[str, Any]:
    findings = component_findings(args.sbom)
    dd = {"scan_type": "SBOM Security Toolkit", "product_name": args.product_name, "engagement_name": args.engagement_name, "scan_date": now().split("T", 1)[0], "minimum_severity": args.minimum_severity, "findings": [{"title": f["title"], "severity": "High" if f.get("level") == "error" else "Medium" if f.get("level") == "warning" else "Info", "description": f.get("message", ""), "component_name": f.get("component", ""), "component_version": f.get("version", ""), "unique_id_from_tool": f.get("fingerprint"), "references": f.get("purl", "")} for f in findings]}
    out = Path(args.out)
    write_json(out, dd)
    return {"path": str(out), "findings": len(dd["findings"]), "note": "DefectDojo import payload scaffold."}


def generate_ci(args: argparse.Namespace) -> Dict[str, Any]:
    provider = args.provider
    out_dir = Path(args.out_dir)
    ensure_dir(out_dir)
    files: Dict[str, str] = {}
    if provider in {"all", "github"}:
        files["github"] = str(write_text(out_dir / "github-pr-check.yml", '''name: SBOM Security Toolkit PR Check
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: read
  security-events: write
jobs:
  sbom-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python -m sbomops.repo_intake analyze . --out-dir reports/repo-intake --dependency-health --fuzz
      - run: python -m sbomops.integrations sarif --sbom reports/repo-intake/sbom.cdx.json --out reports/sarif/sbom-security-toolkit.sarif || true
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/sarif/sbom-security-toolkit.sarif
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sbom-security-toolkit-evidence
          path: reports/
'''))
    if provider in {"all", "gitlab"}:
        files["gitlab"] = str(write_text(out_dir / "gitlab-ci.yml", '''sbom_security_toolkit:
  image: python:3.11
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m sbomops.repo_intake analyze . --out-dir reports/repo-intake --dependency-health --fuzz
    - python -m sbomops.integrations sarif --sbom reports/repo-intake/sbom.cdx.json --out reports/sarif/sbom-security-toolkit.sarif || true
  artifacts:
    when: always
    paths:
      - reports/
'''))
    if provider in {"all", "jenkins"}:
        files["jenkins"] = str(write_text(out_dir / "Jenkinsfile", '''pipeline {
  agent any
  stages {
    stage('SBOM Security Toolkit') {
      steps {
        sh 'python3 -m pip install -r requirements.txt'
        sh 'python3 -m sbomops.repo_intake analyze . --out-dir reports/repo-intake --dependency-health --fuzz'
      }
    }
  }
  post { always { archiveArtifacts artifacts: 'reports/**', allowEmptyArchive: true } }
}
'''))
    if provider in {"all", "circleci"}:
        files["circleci"] = str(write_text(out_dir / "circleci-config.yml", '''version: 2.1
jobs:
  sbom-security-toolkit:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m sbomops.repo_intake analyze . --out-dir reports/repo-intake --dependency-health --fuzz
      - store_artifacts:
          path: reports
workflows:
  sbom-security:
    jobs:
      - sbom-security-toolkit
'''))
    if provider in {"all", "buildkite"}:
        files["buildkite"] = str(write_text(out_dir / "buildkite-pipeline.yml", '''steps:
  - label: ':shield: SBOM Security Toolkit'
    command:
      - 'python3 -m pip install -r requirements.txt'
      - 'python3 -m sbomops.repo_intake analyze . --out-dir reports/repo-intake --dependency-health --fuzz'
    artifact_paths:
      - 'reports/**/*'
'''))
    if provider in {"all", "azure"}:
        files["azure"] = str(write_text(out_dir / "azure-pipelines.yml", '''trigger:
  - main
pr:
  - main
pool:
  vmImage: ubuntu-latest
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
  - script: pip install -r requirements.txt
  - script: python -m sbomops.repo_intake analyze . --out-dir reports/repo-intake --dependency-health --fuzz
  - publish: reports
    artifact: sbom-security-toolkit-evidence
'''))
    return {"provider": provider, "files": files}


def generate_k8s(args: argparse.Namespace) -> Dict[str, Any]:
    base = Path(args.out_dir)
    helm = base / "helm" / "sbom-security-toolkit"
    templates = helm / "templates"
    ensure_dir(templates)
    write_yaml(helm / "Chart.yaml", {"apiVersion": "v2", "name": "sbom-security-toolkit", "description": "Self-hosted SBOM Security Toolkit", "type": "application", "version": "0.1.0", "appVersion": "2.5.0"})
    write_yaml(helm / "values.yaml", {"image": {"repository": "sbom-security-toolkit", "tag": "2.5.0", "pullPolicy": "IfNotPresent"}, "web": {"replicas": 1, "resources": {"requests": {"cpu": "250m", "memory": "512Mi"}, "limits": {"cpu": "1", "memory": "1Gi"}}}, "worker": {"replicas": 1, "resources": {"requests": {"cpu": "500m", "memory": "1Gi"}, "limits": {"cpu": "2", "memory": "4Gi"}}, "maxConcurrentJobs": 1}, "postgres": {"external": False, "host": ""}, "redis": {"external": False, "host": ""}, "s3": {"bucket": "", "prefix": "sbom-security-toolkit"}, "oidc": {"enabled": False, "issuer": "", "clientIdSecretRef": "sst-oidc-client-id", "clientSecretSecretRef": "sst-oidc-client-secret"}, "ingress": {"enabled": False, "className": "", "host": "sst.example.com", "tlsSecret": ""}})
    write_text(templates / "deployment.yaml", '''apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels: { app: sbom-security-toolkit, component: web }
  template:
    metadata:
      labels: { app: sbom-security-toolkit, component: web }
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python3", "-m", "sbomops.workbench.server", "--host", "0.0.0.0", "--port", "8080"]
          ports: [{ containerPort: 8080 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels: { app: sbom-security-toolkit, component: worker }
  template:
    metadata:
      labels: { app: sbom-security-toolkit, component: worker }
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python3", "-m", "sbomops.cloud", "worker"]
''')
    write_text(templates / "service.yaml", '''apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  selector: { app: sbom-security-toolkit, component: web }
  ports:
    - name: http
      port: 80
      targetPort: 8080
''')
    write_text(base / "README.md", "# Kubernetes / Helm deployment scaffold\n\nConfigure external Postgres, Redis, S3-compatible storage, OIDC, ingress, and secrets before exposing the service beyond a trusted network.\n")
    return {"helm_chart": str(helm), "templates": [str(p) for p in sorted(templates.glob("*.yaml"))]}


def write_oidc(args: argparse.Namespace) -> Dict[str, Any]:
    cfg = {"oidc": {"enabled": True, "issuer": args.issuer, "client_id_env": args.client_id_env, "client_secret_env": args.client_secret_env, "allowed_domains": [x.strip() for x in args.allowed_domains.split(",") if x.strip()], "default_role": args.default_role, "admin_groups": [x.strip() for x in args.admin_groups.split(",") if x.strip()], "role_claim": args.role_claim, "created_at": now()}}
    out = Path(args.out)
    write_yaml(out, cfg)
    return {"path": str(out), "enabled": True}


def write_worker_limits(args: argparse.Namespace) -> Dict[str, Any]:
    cfg = {"worker_limits": {"max_repo_mb": args.max_repo_mb, "max_sbom_mb": args.max_sbom_mb, "max_evidence_mb": args.max_evidence_mb, "job_timeout_seconds": args.job_timeout_seconds, "fuzz_timeout_seconds": args.fuzz_timeout_seconds, "max_concurrent_jobs": args.max_concurrent_jobs, "retry_count": args.retry_count, "allowed_workflows": [x.strip() for x in args.allowed_workflows.split(",") if x.strip()], "allow_repo_code_execution": False, "allow_ai_uploads_by_default": False, "created_at": now()}}
    out = Path(args.out)
    write_yaml(out, cfg)
    return {"path": str(out), "limits": cfg["worker_limits"]}


def _resolve_target(ref: str) -> str:
    if ref.startswith("env:"):
        return os.environ.get(ref.split(":", 1)[1], "")
    return os.environ.get(ref, ref if ref.startswith("http") or "@" in ref else "")


def notify(args: argparse.Namespace) -> Dict[str, Any]:
    event = {"event": args.event, "severity": args.severity, "title": args.title, "message": args.message, "project": args.project, "ts": now()}
    target = _resolve_target(args.target_ref)
    out = {"event": event, "target_ref": args.target_ref, "sent": False, "mode": "dry-run"}
    if args.send:
        if not target:
            raise SystemExit(f"Target reference {args.target_ref!r} did not resolve to a target value")
        if args.type in {"webhook", "slack"}:
            body = json.dumps(event if args.type == "webhook" else {"text": f"*{args.title}*\n{args.message}", "event": event}).encode()
            req = urllib.request.Request(target, data=body, headers={"Content-Type": "application/json"}, method="POST")
            with urllib.request.urlopen(req, timeout=10) as resp:
                out.update({"sent": True, "status": getattr(resp, "status", None), "mode": "sent"})
        elif args.type == "email":
            msg = EmailMessage(); msg["From"] = args.email_from; msg["To"] = target; msg["Subject"] = args.title; msg.set_content(args.message)
            with smtplib.SMTP(args.smtp_host, args.smtp_port, timeout=10) as smtp:
                smtp.send_message(msg)
            out.update({"sent": True, "mode": "sent"})
    write_json(Path(args.out), {"notification": out, "payload": event})
    return out


def github_app_scaffold(args: argparse.Namespace) -> Dict[str, Any]:
    out = Path(args.out_dir)
    ensure_dir(out)
    app = {"github_app": {"enabled": True, "app_id_env": "SST_GITHUB_APP_ID", "private_key_secret_ref": "github-app-private-key", "webhook_secret_ref": "github-app-webhook-secret", "permissions": {"contents": "read", "pull_requests": "write", "checks": "write", "security_events": "write"}, "events": ["pull_request", "push", "check_suite"], "default_workflow": args.workflow, "release_decision_mode": args.release_decision_mode}}
    write_yaml(out / "github-app.yml", app)
    write_text(out / "README.md", "# GitHub App scaffold\n\nCreate a GitHub App with read-only repository content access, checks write access, pull request write access, and security-events write access. Store secrets via the toolkit secret reference model.\n")
    return {"path": str(out / "github-app.yml")}


def demo_enterprise(args: argparse.Namespace) -> Dict[str, Any]:
    sample_dir = Path(args.out_dir)
    ensure_dir(sample_dir)
    sbom = sample_dir / "sample.cdx.json"
    write_json(sbom, {"bomFormat": "CycloneDX", "specVersion": "1.5", "version": 1, "metadata": {"component": {"name": "demo-app", "type": "application", "version": "1.0.0"}}, "components": [{"type": "library", "name": "demo-missing-version", "purl": "pkg:npm/demo-missing-version"}, {"type": "library", "name": "demo-stale", "version": "latest", "purl": "pkg:pypi/demo-stale@latest"}]})
    sarif = sample_dir / "sbom-security-toolkit.sarif"
    export_sarif(argparse.Namespace(sbom=str(sbom), out=str(sarif), project="demo-enterprise", release_decision=""))
    vex = sample_dir / "openvex.json"
    export_openvex(argparse.Namespace(sbom=str(sbom), out=str(vex), vulnerability="CVE-DEMO-0001", status="under_investigation", justification="component_not_analyzed", impact_statement="Demo only", action_statement="Review before release", author="SBOM Security Toolkit Demo"))
    generate_ci(argparse.Namespace(provider="all", out_dir=str(sample_dir / "ci")))
    write_worker_limits(argparse.Namespace(out=str(sample_dir / "worker-limits.yml"), max_repo_mb=500, max_sbom_mb=100, max_evidence_mb=1000, job_timeout_seconds=3600, fuzz_timeout_seconds=300, max_concurrent_jobs=1, retry_count=1, allowed_workflows="analyze,analyze-everything,repo-intake,fuzz-all-timed"))
    summary = {"demo_dir": str(sample_dir), "sample_sbom": str(sbom), "sarif": str(sarif), "openvex": str(vex), "ci_dir": str(sample_dir / "ci"), "created_at": now()}
    write_json(sample_dir / "demo-summary.json", summary)
    return summary


def main(argv: List[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Production integrations, exports, notifications, CI/CD, and deployment scaffolds")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("sarif"); p.add_argument("--sbom", required=True); p.add_argument("--out", default="reports/sarif/sbom-security-toolkit.sarif"); p.add_argument("--project", default=""); p.add_argument("--release-decision", default="")
    p = sub.add_parser("openvex"); p.add_argument("--sbom", required=True); p.add_argument("--out", default="reports/openvex/openvex.json"); p.add_argument("--vulnerability", default=""); p.add_argument("--status", choices=["not_affected", "affected", "fixed", "under_investigation"], default="under_investigation"); p.add_argument("--justification", default="component_not_analyzed"); p.add_argument("--impact-statement", default="Generated by SBOM Security Toolkit for review."); p.add_argument("--action-statement", default="Review and update VEX status before external distribution."); p.add_argument("--author", default="SBOM Security Toolkit")
    p = sub.add_parser("jira-export"); p.add_argument("--sbom", required=True); p.add_argument("--out", default="reports/integrations/jira-issues.json"); p.add_argument("--project-key", default="SEC"); p.add_argument("--issue-type", default="Task")
    p = sub.add_parser("defectdojo-export"); p.add_argument("--sbom", required=True); p.add_argument("--out", default="reports/integrations/defectdojo-import.json"); p.add_argument("--product-name", default="SBOM Security Toolkit Project"); p.add_argument("--engagement-name", default="SBOM Review"); p.add_argument("--minimum-severity", default="Info")
    p = sub.add_parser("ci-generate"); p.add_argument("--provider", choices=["all", "github", "gitlab", "jenkins", "circleci", "buildkite", "azure"], default="all"); p.add_argument("--out-dir", default="reports/ci-templates")
    p = sub.add_parser("k8s-generate"); p.add_argument("--out-dir", default="deploy/kubernetes")
    p = sub.add_parser("oidc-config"); p.add_argument("--issuer", required=True); p.add_argument("--out", default="configs/generated/integrations/oidc.yml"); p.add_argument("--client-id-env", default="SST_OIDC_CLIENT_ID"); p.add_argument("--client-secret-env", default="SST_OIDC_CLIENT_SECRET"); p.add_argument("--allowed-domains", default=""); p.add_argument("--default-role", default="analyst"); p.add_argument("--admin-groups", default=""); p.add_argument("--role-claim", default="groups")
    p = sub.add_parser("worker-limits"); p.add_argument("--out", default="configs/generated/integrations/worker-limits.yml"); p.add_argument("--max-repo-mb", type=int, default=500); p.add_argument("--max-sbom-mb", type=int, default=100); p.add_argument("--max-evidence-mb", type=int, default=1000); p.add_argument("--job-timeout-seconds", type=int, default=3600); p.add_argument("--fuzz-timeout-seconds", type=int, default=300); p.add_argument("--max-concurrent-jobs", type=int, default=1); p.add_argument("--retry-count", type=int, default=1); p.add_argument("--allowed-workflows", default="analyze,analyze-everything,repo-intake,dependency-health,fuzz-all-timed")
    p = sub.add_parser("notify"); p.add_argument("--type", choices=["webhook", "slack", "email"], default="webhook"); p.add_argument("--target-ref", default="SST_WEBHOOK_URL"); p.add_argument("--event", default="release_blocked"); p.add_argument("--severity", default="warning"); p.add_argument("--title", default="SBOM Security Toolkit notification"); p.add_argument("--message", default="A configured event occurred."); p.add_argument("--project", default=""); p.add_argument("--out", default="reports/notifications/last-notification.json"); p.add_argument("--send", action="store_true"); p.add_argument("--smtp-host", default="localhost"); p.add_argument("--smtp-port", type=int, default=25); p.add_argument("--email-from", default="sst@example.local")
    p = sub.add_parser("github-app-scaffold"); p.add_argument("--out-dir", default="configs/generated/integrations/github-app"); p.add_argument("--workflow", default="analyze-everything"); p.add_argument("--release-decision-mode", choices=["comment", "check", "block"], default="check")
    p = sub.add_parser("demo-enterprise"); p.add_argument("--out-dir", default="reports/demo-enterprise")
    args = ap.parse_args(argv)
    if args.cmd == "sarif": out = export_sarif(args)
    elif args.cmd == "openvex": out = export_openvex(args)
    elif args.cmd == "jira-export": out = export_jira(args)
    elif args.cmd == "defectdojo-export": out = export_defectdojo(args)
    elif args.cmd == "ci-generate": out = generate_ci(args)
    elif args.cmd == "k8s-generate": out = generate_k8s(args)
    elif args.cmd == "oidc-config": out = write_oidc(args)
    elif args.cmd == "worker-limits": out = write_worker_limits(args)
    elif args.cmd == "notify": out = notify(args)
    elif args.cmd == "github-app-scaffold": out = github_app_scaffold(args)
    elif args.cmd == "demo-enterprise": out = demo_enterprise(args)
    else: raise SystemExit(2)
    print(json.dumps(out, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
