name: ClusterFuzzLite Nightly
on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:
jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          fuzz-seconds: 600
          mode: 'batch'
